### ISSUE TITLE
Version 1.0.0 Method not found: gateway_protocol.Gateway/DeployWorkflow

### ISSUE THREAD

**Issue by nachoroncero** [camunda-community-hub/zeebe-hazelcast-exporter#114]
Hello,

I have just downloaded the Zeebe version 1.0.0 and I cannot deploy a bpmn file in monitor. 

This is the error: Method not found: gateway_protocol.Gateway/DeployWorkflow

I read that I have to update the exporter o something similar, what do I have to do? 

Help please

**Comment by saig0** [comment]
Hi @nachoroncero,

for Zeebe 1.0.0, you need the following components:
* [Hazelcast exporter 1.0.0](https://github.com/camunda-community-hub/zeebe-hazelcast-exporter/releases/tag/1.0.0)
* [Zeebe Simple Monitor 2.0.0](https://github.com/camunda-community-hub/zeebe-simple-monitor/releases/tag/2.0.0)

Does it work now?
If not, please share more details about the failure.

**Comment by saig0** [comment]
Related issue: camunda-community-hub/zeebe-simple-monitor#262

**Comment by nachoroncero** [comment]
It is true that I am using Zeebe Simple Monitor 1.0.0, but because I don’t
know where I can get the 2.0.0 version to work with docker-compose…

Is there any link to download Zeebe 1.0.0 and Monitor 2.0.0 for
docker-compose?

Thank you

**Comment by saig0** [comment]
I answered this question here: https://github.com/camunda-community-hub/zeebe-simple-monitor/issues/262#issuecomment-863813852

Closing this issue in favor of camunda-community-hub/zeebe-simple-monitor#262
