### ISSUE TITLE
How zeebe-hazelcast-exporter supports zeebe cluster deployment？

### ISSUE THREAD

**Issue by bugbugmaker** [camunda-community-hub/zeebe-hazelcast-exporter#205]
https://github.com/camunda-community-hub/zeebe-docker-compose/blob/master/cluster/docker-compose.yml

How to implement client monitoring zeeeb cluster? Do I need to configure port 5701 of the exporter of each node?
hazelcastConnection is a string of multiple ips and ports.
`
	final ClientConfig clientConfig = new ClientConfig();
	clientConfig.getNetworkConfig().setAddresses(Arrays.asList(hazelcastConnection.split(",")));
`
Or is it ok as long as clustName is set to dev port with 5701? like this
`clientConfig.setClusterName("dev");
clientConfig.getNetworkConfig().addAddress("XXXXX:5701");`

**Comment by saig0** [comment]
If you have a Zeebe cluster, I recommend using an external Hazelcast instance/cluster. 

Look at the [README](https://github.com/camunda-community-hub/zeebe-hazelcast-exporter#connect-to-an-externalremote-hazelcast-cluster) on how to configure it.
