### ISSUE TITLE
Update C# connector to latest

### ISSUE THREAD

**Issue by Zelldon** [camunda-community-hub/zeebe-hazelcast-exporter#6]
Requirements:

 * migrate .net project to .net core
 * migrate to latest hazelcast exporter and protobuf version
 * add tests if possible
 * take a look at the current travis ci config
 * update release pipeline if possible

**Comment by saig0** [comment]
* use one ring buffer instead of multiple topics
* read the generic record (i.e. any type), unpack and invoke the listeners

See #29.

**Comment by MrRickwi** [comment]
Would like to see this project come back to life. Especially since Hazelcast is now updating to Hazelcast IMDG 4 which is already used in Zeebe. Did first tests by myself, and I'm able to connect ot the Hazelcast exporter, but no events are published. Missing information on how to correctly subscribe to hazelcast exporter events.

**Comment by MrRickwi** [comment]
Possibly code could look like:

```
                // Start the Hazelcast Client and connect to an already running Hazelcast Cluster on 127.0.0.1
                var loggerFactory = LoggerFactory.Create(builder => { builder.AddConsole(); });
                var options = HazelcastOptions.Build();
                options.Logging.LoggerFactory.Creator = () => loggerFactory;
                var hazelCastClient = HazelcastClientFactory.CreateClient(options);
                await hazelCastClient.StartAsync();
                var topic = await hazelCastClient.GetTopicAsync<byte[]>("zeebe-deployments");

                // Add a Listener to the Topic
                await topic.SubscribeAsync(e =>
                    e.Message((hTopic, args) => Console.WriteLine($@"{hTopic.Name}: {args.Payload}")));

                // Return the client
                return hazelCastClient;
```
